name: Mark PR as Ready to Review
description: Converts the given pull request from a draft to be ready-to-review
branding:
  icon: git-pull-request
  color: gray-dark

inputs:
  pull-request-number:
    required: false
    description: GitHub pull request number
    default: ${{ github.event.number }}
  owner:
    required: false
    description: GitHub pull request's owner or organization
    default: ${{  github.repository_owner }}
  repo:
    required: false
    description: GitHub pull request's repo name
    default: ${{ github.event.repository.name }}
  token:
    required: false
    description: Github Token used to make API request to mutate pull requests
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Move PR from draft to ready-to-review
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        gh pr ready --repo  ${{ inputs.owner }}/${{ inputs.repo }} ${{ inputs.pull-request-number }}
      shell: bash
      
    - name: Read repo and pr info via GraphQL
      uses: octokit/graphql-action@v2.2.20
      id: get_issue_info
      with:
        query: |
          query GetPrInfo($owner:String!, $repo:String!, $prnumber:Int!) {
            repository: repository(owner:$owner, name:$repo) {
              id
              nameWithOwner
              pullRequest(number:$prnumber) {
                  title
                  id
                  number
                  createdAt
                  closedAt
                  isDraft
              }
            }
          }
        owner: ${{ inputs.owner }}
        repo: ${{ inputs.repo }}
        prnumber: ${{ inputs.pull-request-number }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Show Repo Info
      env:
        REPOSITORY_DATA: ${{ steps.get_issue_info.outputs.data }}
      run: |
        echo "issue/repo info after change: ${REPOSITORY_DATA}"
      shell: bash
